### ISSUE TITLE
Update to `typedoc-default-themes` broke CI build

### ISSUE THREAD

**Issue by kamranayub** [sebastian-lenz/typedoc#113]
There was an update to the `typedoc-default-themes` npm package from 0.3.3 to 0.3.4, and our CI build is now broken with typedoc 0.3.4. Is there a way to fix this? I think the package.json needs to be fixed for earlier versions (installing previous typedoc still pulls latest themes dependency).

```
typedoc@0.3.4 node_modules/typedoc
├── progress@1.1.8
├── marked@0.3.3
├── shelljs@0.4.0
├── fs-extra@0.16.5 (jsonfile@2.2.1, graceful-fs@3.0.8)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── typedoc-default-themes@0.3.4
├── highlight.js@8.6.0
├── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
└── typescript@1.4.1

Executing typedoc...
/home/travis/build/excaliburjs/excaliburjs.github.io/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:69
      throw new Exception("Missing helper: '" + arguments[arguments.length-1].
            ^
Error
    at Object.<anonymous> (/home/travis/build/excaliburjs/excaliburjs.github.io/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/exception.js:29:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/excaliburjs/excaliburjs.github.io/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:3:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
child_process.js:1389
    throw err;
```

**Comment by kamranayub** [comment]
Workaround issue by expliciting depending on `typedoc-default-themes` version `0.3.3` in your package.json

**Comment by sebastian-lenz** [comment]
The update should only include minor changes to the theme, this is unexpected.

**Comment by sebastian-lenz** [comment]
Did you update TypeDoc as well?

**Comment by kamranayub** [comment]
No, we left it untouched, we just wanted it to build using 0.3.4 since that's what it was using already.

**Comment by sebastian-lenz** [comment]
Okay, the new templates reference a helper that's not part of TypeDoc 0.3.4, everything works fine with the latest versions. I will bind the theme and application version more tightly from now on.
