### ISSUE TITLE
TypeError:  Cannot call method 'equals' of undefined

### ISSUE THREAD

**Issue by agponte** [sebastian-lenz/typedoc#119]
We've been using typedoc for a while, thank you BTW!!  I updated to the latest version to get TS 1.5 support, the update/install went perfectly but I cannot generate documentation.  I've tried node v0.12 and v0.10 and both error out.

Here is the stacktrace:
```
Using TypeScript 1.5.0-beta from C:\Program Files (x86)\nodejs\node_modules\typedoc\node_modules\typescript\bin

C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:6856
                    type.constraint.equals(this.constraint) &&
                                    ^
TypeError: Cannot call method 'equals' of undefined
    at TypeParameterType.equals (C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:6856:37)
    at Function.Type.isTypeListEqual (C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:6055:35)
    at C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:5185:52
    at Array.forEach (native)
    at C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:5184:52
    at Array.forEach (native)
    at C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:5182:52
    at Array.forEach (native)
    at ImplementsPlugin.analyzeClass (C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:5161:46)
    at C:\Program Files (x86)\nodejs\node_modules\typedoc\bin\typedoc.js:5226:35
```

**Comment by agponte** [comment]
I found the offending class in our code base but it compiles fine outside of typedoc.  I comment out the entire class, re-run typedoc and I get a host of other issues from the TS compiler that are not a problem in production.

I downgraded to typedoc v0.3.3 and everything is running fine again except I would like TS 1.5 support because that is what we are using in production.

Let me know how I can help you track this down...thanks!

**Comment by jonnermut** [comment]
Same here

Using TypeScript 1.5.0-beta from /git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/typescript/bin

/git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:6856
                    type.constraint.equals(this.constraint) &&
                                    ^
TypeError: Cannot call method 'equals' of undefined
    at TypeParameterType.equals (/git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:6856:37)
    at Function.Type.isTypeListEqual (/git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:6055:35)
    at /git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:5185:52
    at Array.forEach (native)
    at /git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:5184:52
    at Array.forEach (native)
    at /git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:5182:52
    at Array.forEach (native)
    at ImplementsPlugin.analyzeClass (/git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:5161:46)
    at /git/refactor/tools/FormEngine/node_modules/typedoc/bin/typedoc.js:5226:35
:typedoc FAILED

**Comment by jonnermut** [comment]
version 0.33 gave a different error:

Using TypeScript 1.4.1 from /git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/typescript/bin

/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:69
      throw new Exception("Missing helper: '" + arguments[arguments.length-1].
            ^
Error: Missing helper: 'ifSignature'
    at new Error (native)
    at Error.Exception (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/exception.js:16:41)
    at ReferenceType.<anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:69:13)
    at Object.eval (eval at <anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:102)
    at Object.prog [as fn] (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:15)
    at ReferenceType.<anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:181:22)
    at Object.eval (eval at <anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:35)
    at Object.prog [as fn] (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:15)
    at ReferenceType.<anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/base.js:181:22)
    at Object.eval (eval at <anonymous> (/git/refactor/tools/FormEngine/node_modules/typedoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:35)
:typedoc FAILED

**Comment by sebastian-lenz** [comment]
Hi, thank you both for reporting this. I've found a potential flaw in the equality check for type parameters and I've included a quick fix.

For being able to better understand what's going wrong it would be great if you could describe the code that causes this problem. It must be a class implementing an interface with a generic type parameter. I guess that either the interface or both the interface and the class use a type parameter without a type constraint? I would like to add this as a test case.

**Comment by jonnermut** [comment]
is there any way to know what file its processing? code base it way too big to try and work it out

**Comment by jonnermut** [comment]
Thanks for fixing this by the way. I know you just put out a release, but would be awesome to get this into the NPM soon, as it's stopping us upgrading to typescript 1.5, which has so much cool new stuff!

**Comment by sebastian-lenz** [comment]
You should be able to see where the error is thrown if you add the <code>--verbose</code> option. TypeDoc will print the symbol and file names while processing them.

I would be happy to publish a new version if we can ensure that this error is fixed.

**Comment by jonnermut** [comment]
Hi Sebastian, think its this file: 
https://dl.dropboxusercontent.com/u/1341356/EventDispatcher.ts

Which indeed has a class implementing a generic interface (EventDispatcher)

**Comment by sebastian-lenz** [comment]
Great, I've added you code as a test case, of course I've removed all logic so only the bare signatures are left over. The new version passes the test so I think the bugfix is sufficient.

I've just pushed version 0.3.7 to NPM so you can try it out for yourself.
