### ISSUE TITLE
Unexpected token ∩╗┐

### ISSUE THREAD

**Issue by hawk4031** [sebastian-lenz/typedoc#133]
Hello! I am attempting to use Typedoc 0.3.8 but I'm receiving the error below. The command I'm running is:

    typedoc --mode modules --out docs\ .\Engineering\App\flexViewApp.ts

Any suggestions?

    Using TypeScript 1.5.3 from C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\bin
    undefined:1
    ∩╗┐{
    ^
    SyntaxError: Unexpected token ∩╗┐
    at Object.parse (native)
    at PackagePlugin.onBeginResolve (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5334:
    48)
    at Converter.EventDispatcher.dispatch (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js
    :102:34)
    at Converter.resolve (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:2048:22)
    at Converter.convert (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:2005:36)
    at Application.convert (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:430:41)
    at Application.bootstrapFromCommandline (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.
    js:276:36)
    at new Application (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:231:22)
    at Object.<anonymous> (C:\Users\charlie25594\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc:4:12)
    at Module._compile (module.js:460:26)

**Comment by sebastian-lenz** [comment]
This looks like an error in your <code>package.json</code> file. TypeDoc picks up the nearest <code>package.json</code> and parses it. Could you check it if there is anything suspicious?

**Comment by hawk4031** [comment]
There doesn't appear to be anything weird going on. I have pasted the contents below. I checked in Notepad++ for weird characters and there's nothing out of the ordinary. Thoughts?

    {
        "name": "FlexViewWeb",
        "version": "1.0.0",   
        "dependencies": {},
        "devDependencies": {
            "del": "^1.2.0",
            "gulp": "^3.9.0",
            "gulp-debug": "^2.0.1",
            "gulp-htmlmin": "^1.1.3",
            "gulp-inject": "^1.3.1",
            "gulp-rimraf": "^0.1.1",
            "gulp-sourcemaps": "^1.5.2",
            "gulp-tslint": "^3.0.0-beta",
            "gulp-typescript": "^2.7.7",
            "gulp-uglify": "^1.2.0",
            "gulp-util": "^3.0.6"
        }
    }

**Comment by poelstra** [comment]
Byte Order Mark maybe?

**Comment by hawk4031** [comment]
I didn't know there was such a thing until you said that. The Wiki article on it don't show those same characters so I don't know if that's it. Is there something I can check into to verify?

**Comment by GaelFG** [comment]
I just had the same issue.
In the parent folder of the source folder, there was the package.json of my project wich was encoded as utf-8 with bom. 
Saving this file as utf-8 without bom corrected the problem. (It could probably be corrected in the parser)

**Comment by hawk4031** [comment]
@GaelFG thanks for that information! That appears to have worked. Since Visual Studio created the file, I assume it just defaulted to UTF-8 with BOM.
